### ISSUE TITLE
Constraint counts for the accumulation verifier

### ISSUE THREAD

**Issue by srinathsetty** [arkworks-rs/accumulation#46]
What is the easiest way to produce data used in Figure 7 here: https://eprint.iacr.org/2020/1618.pdf? Also, how about the number of constraints for the accumulation verifier for the NARK for R1CS in this paper?

It looks like the examples (e.g., scaling-as) report the prover time/verifier time/etc. but not the number of constraints of the accumulation verifier.

**Comment by Pratyush** [comment]
Hey Srinath!

I pushed a commit which provides a breakdown of constraints, matching the numbers reported in the figure. To obtain these numbers, you can run the following commands:

* for R1CS NARK accumulation: `cargo test constraints::tests::simple_accumulation_test --features r1cs-nark-as  -- --nocapture --test-threads=1`
* for IPA PC accumulation: `cargo test constraints::tests::simple_accumulation_test --features ipa-pc-as  -- --nocapture --test-threads=1` (You might need to manually change the degree being accumulated)
* for trivial PC accumulation: `cargo test constraints::tests::simple_accumulation_test --features trivial-pc-as  -- --nocapture --test-threads=1`

**Comment by srinathsetty** [comment]
Thanks a lot @Pratyush! This worked.

On a related note, when I do `cargo build --release --example scaling-nark --features="hp-as r1cs-nark-as"`, it successfully builds the binaries. But when I run, say:
`./target/release/examples/scaling-nark 10 12 1`

I get the following error:
================ Benchmarking NARK without zk ================
thread 'main' panicked at 'assertion failed: R1CSNark::<Affine,\n           PoseidonSponge<Fq>>::verify(&ivk, &[v, a, a, a, a], &proof,\n                                       Some(PoseidonSponge::new()))', examples/scaling-nark.rs:95:9

Another minor issue is that it seems like the following line in scaling-nark.rs:
`if args.len() < 4 || args[1] == "-h" || args[1] == "--help"` 
should be: 
`if args.len() < 3 || args[1] == "-h" || args[1] == "--help"`, right?

**Comment by Pratyush** [comment]
Ah thanks for pointing that out, I've fixed it now =)

**Comment by srinathsetty** [comment]
It now works, thanks! :)
